### ISSUE TITLE
Zenodo Access

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-oslo/rdm-lookup#28]
Hi @morj-uio or @sveinugu, can you please kindly enable Zenodo for this repository https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization Thank you!

**Comment by sveinugu** [comment]
I cannot see Zenodo in the list.  @nazeeefa I think you need to do this first:


https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps



________________________________
From: Nazeeefa ***@***.***>
Sent: 22 February 2023 09:37
To: elixir-oslo/rdm-lookup
Cc: Sveinung Gundersen; Mention
Subject: [elixir-oslo/rdm-lookup] Zenodo Access (Issue #28)


Hi @morj-uio<https://github.com/morj-uio> or @sveinugu<https://github.com/sveinugu>, can you please kindly enable Zenodo for this repository https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization Thank you!

**Comment by Nazeeefa** [comment]
I see Zenodo in the list from Settings of my personal account. You need to log in to Zenodo via GitHub account of ELIXIR Oslo then you will be able to enable Zenodo for this repository. Let me know if it doesn't work. Thanks

**Comment by Nazeeefa** [comment]
Thanks @sveinugu, sent the request ✅

**Comment by Nazeeefa** [comment]
@sveinugu @morj-uio you may have received request notification again to enable Zenodo, could you kindly accept? Thanks

**Comment by morj-uio** [comment]
Request accepted.

1. mar. 2023 kl. 16:48 skrev Nazeeefa ***@***.******@***.***>>:



@sveinugu<https://github.com/sveinugu> @morj-uio<https://github.com/morj-uio> you may have received request notification again to enable Zenodo, could you kindly accept? Thanks
