### ISSUE TITLE
Mention ETT in footer

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-oslo/rdm-lookup#29]
1. Text could be "Built with ETT" or 'Theme: ELIXIR ToolKit Theme'
2. If possible, 1 followed by ETT logo^
3. Link to GitHub repo https://elixir-belgium.github.io/elixir-toolkit-theme

**Comment by korbinib** [comment]
This could be a simple PR instead of an issue.

**Comment by Nazeeefa** [comment]
I have and prefer to create one to share idea/thought, and it's good for communication related to PRs. PRs can sometimes include multiple changes that need to be addressed, then it becomes even more important to have conversations organised properly. Thank you for understanding
